<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/5
     * Time: 9:12
     */
namespace app\index\controller;

use think\Controller;

class Base extends Controller
{
    public function __initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}
